if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
"
"
nnoremap <SPACE> <Nop>
let mapleader = "\<Space>"


"" file changes
nnoremap <leader>qq :q<cr>
nnoremap <leader>qa :qa!<cr>
nnoremap <leader>qw :wq!<cr>
nnoremap <leader>fs :w<cr>
nnoremap <leader>qd :qa!<cr>

nnoremap <leader>xx :x!<cr>

nnoremap <leader>ee :e!<cr>

noremap <silent><leader>rb :bufdo e!<cr>

nnoremap <esc> :noh<return><esc>

"""Source (reload) your vimrc. Type space, s, o in sequence to trigger
nmap <leader>so :source $MYVIMRC<cr>

set encoding=utf-8

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab
set autoindent

" Use one space, not two, after punctuation.
set nojoinspaces

set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands

syntax on

" Leader
nnoremap <leader>ntt :NERDTreeToggle<cr>
nnoremap <leader>ntr :NERDTreeFocus<cr>
nnoremap <leader>ntf :NERDTreeFind<cr>

" Make it obvious where 80 characters is
set textwidth=80

" Numbers
set number
set numberwidth=5

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<Tab>"
    else
        return "\<C-p>"
    endif
endfunction
inoremap <Tab> <C-r>=InsertTabWrapper()<CR>
inoremap <S-Tab> <C-n>

" Switch between the last two files
nnoremap <Leader><Leader> <C-^>

" Tree mappings
nnoremap <leader>ntt :NERDTreeToggle<cr>
nnoremap <leader>ntr :NERDTreeFocus<cr>
nnoremap <leader>ntf :NERDTreeFind<cr>



call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
call plug#end()
