- name: setup machine
  hosts: localhost
  become: true
  vars:
    - nodejs_major_version: 16
    - asdf_version_branch: v0.9.0

  tasks:
    - name: install zsh (Ubuntu)
      apt:
        name: zsh
        state: present
        update_cache: true
      tags:
        - zsh

    - name: change zsh shell
      shell: chsh -s $(which zsh)
      become: True
      tags:
        - zsh
    - name: install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      become: True
      tags:
        - zsh
    - name: get zsh path
      shell: which zsh
      register: zsh_path

    - name: change shell to zsh
      user:
        name: root
        shell: /usr/bin/zsh
      become: True

    - name: clone asdf
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: "{{ asdf_version_branch }}"
      become: True
      tags:
        - asdf
    - name: Load asdf in .zshrc
      blockinfile:
        dest: ~/.zshrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK: asdf"
        block: |
          if [ -e "$HOME/.asdf/asdf.sh" ]; then
            source $HOME/.asdf/asdf.sh
            source $HOME/.asdf/completions/asdf.bash
          fi
      become: true
      tags:
        - asdf
    - name: reload zsh shell
      shell: source ~/.zshrc
      tags:
        - asdf

    - name: add node asdf plugin
      shell: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      become: True
      tags:
        - node
    - name: install node
      shell: asdf install nodejs latest:{{ nodejs_major_version }}
      become: True
      tags:
        - node
    - name: set global node version
      shell:  asdf global nodejs latest:{{ nodejs_major_version }}
      become: True

    - name: add nvim repo
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/stable
      tags:
        - nvim
    - name: install nvim
      apt:
        name: neovim
      tags:
        - nvim
    - name: install ag
      apt:
        name: silversearcher-ag
      tags:
        - nvim
    - name: install vim-plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      tags:
        - nvim
    - name: stow nvim
      shell: stow nvim
      tags:
        - nvim


