- name: setup machine
  hosts: localhost
  become: true

  tasks:
    - name: install zsh
      apt:
        name: zsh
      tags:
        - zsh
    - name: change zsh shell
      shell: chsh -s $(which zsh)
      tags:
        - zsh
    - name: install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: add nvim repo
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/stable
      tags:
        - nvim
    - name: install nvim
      apt:
        name: neovim
      tags:
        - nvim
    - name: install ag
      apt:
        name: silversearcher-ag
      tags:
        - nvim
    - name: install vim-plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      tags:
        - nvim


