- name: setup machine
  hosts: localhost
  become: True
  vars:
    - nodejs_major_version: 16
    - asdf_version_branch: v0.9.0

  tasks:
    - name: install zsh (Ubuntu)
      apt:
        name: zsh
        state: present
        update_cache: true
      tags:
        - zsh
    - name: clone asdf
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: "{{ asdf_version_branch }}"
      become: True
      tags:
        - asdf

    - name: change zsh shell
      shell: chsh -s $(which zsh)
      tags:
        - zsh
    - name: install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags:
        - zsh
    - name: move old .zshrc
      shell: mv ~/.zshrc ~/.zshrc.old

    - name: stow zshrc
      shell: stow oh-my-zsh

    - name: set zsh as default shell
      shell: chsh -h $(which zsh)

    - name: add node asdf plugin
      shell: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      tags:
        - node
    - name: install node
      shell: asdf install nodejs latest:{{ nodejs_major_version }}
      tags:
        - node
    - name: set global node version
      shell:  asdf global nodejs latest:{{ nodejs_major_version }}

    - name: add nvim repo
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/stable
      tags:
        - nvim
    - name: install nvim
      apt:
        name: neovim
      tags:
        - nvim
    - name: install ag
      apt:
        name: silversearcher-ag
      tags:
        - nvim
    - name: install vim-plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      tags:
        - nvim
    - name: stow nvim
      shell: stow nvim
      tags:
        - nvim


