- name: install main
  hosts: localhost
  become: True
  vars:
    - nodejs_major_version: 16
    - ruby_major_version: 2.7

  tasks:
    - name: add node asdf plugin
      shell: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      tags:
        - node
    - name: install node
      shell: asdf install nodejs latest:{{ nodejs_major_version }}
      tags:
        - node
    - name: set global node version
      shell: asdf global nodejs latest:{{ nodejs_major_version }}
      tags:
        - node

    - name: install ruby
      shell: asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
      tags:
        - ruby
    - name: install ruby version
      shell: asdf install ruby latest:{{ ruby_major_version }}
      tags:
        - ruby
    - name: set global ruby version
      shell: asdf global ruby latest:{{ ruby_major_version }}
      tags:
        - ruby

    - name: add nvim repo
      ansible.builtin.apt_repository:
        repo: ppa:neovim-ppa/stable
      tags:
        - nvim
    - name: install nvim
      apt:
        name: neovim
      tags:
        - nvim
    - name: install ag
      apt:
        name: silversearcher-ag
      tags:
        - nvim
    - name: install vim-plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      tags:
        - nvim
    - name: stow nvim
      shell: stow nvim
      tags:
        - nvim