- name: setup machine
  hosts: localhost
  become: true

  vars:
    - asdf_version_branch: v0.9.0

  tasks:
    - name: install zsh (Ubuntu)
      apt:
        name: zsh
        state: present
        update_cache: true
      tags:
        - zsh
    - name: clone asdf
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        version: "{{ asdf_version_branch }}"
      become: True
      tags:
        - asdf
        - zsh

    - name: change zsh shell
      shell: chsh -s $(which zsh)
      tags:
        - zsh
    - name: install oh my zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags:
        - zsh
    - name: move old .zshrc
      shell: mv ~/.zshrc ~/.zshrc.old
      tags:
        - zsh

    - name: stow zshrc
      shell: stow oh-my-zsh
      tags:
        - zsh

    - name: set zsh as default shell
      shell: chsh -s $(which zsh)
      tags:
        - zsh